### ISSUE TITLE
Cannot find reference 'FELToken' and 'ProjectContract' in brownie. 

### ISSUE THREAD

**Issue by Hongchenglong** [FELT-Labs/federated-learning-token#34]
Hello, sir. I met some questions in quickstart.
My version of `eth-brownie` is 1.17.2, but I cannot find reference 'FELToken' and 'ProjectContract' in brownie. 

My error as follow:
```
Running 'scripts/create_plan.py::main'...
  File "<console>", line 1, in <module>
  File "brownie/project/scripts.py", line 69, in run
    return func(*args, **kwargs)
  File "./scripts/create_plan.py", line 18, in main
    project = ProjectContract[-1]
  File "brownie/network/contract.py", line 173, in __getitem__
    return self._contracts[i]
IndexError: list index out of range
```

I am looking forward your reply.

**Comment by Breta01** [comment]
Hi, thanks for your interest.
Quick question, did you follow the instructions: 
https://github.com/FELT-Labs/federated-learning-token#quick-start

What does it print out when you run:
```bash
brownie run deploy -I
```
Where there any errors? Because it looks like this deployment wasn't successful.

**Comment by Hongchenglong** [comment]
> Hi, thanks for your interest. Quick question, did you follow the instructions: https://github.com/FELT-Labs/federated-learning-token#quick-start
> 
> What does it print out when you run:
> 
> ```shell
> brownie run deploy -I
> ```
> 
> Where there any errors? Because it looks like this deployment wasn't successful.

Thank you. I find out why there is this error, Because I filled in the wrong private key in `.env`.
