### ISSUE TITLE
computer configuration

### ISSUE THREAD

**Issue by Hongchenglong** [FELT-Labs/federated-learning-token#35]
Sir, I want to know what computer configuration do I need to run this project?

**Comment by Breta01** [comment]
The code was tested on Linux, but you should also be able to run it on Mac or Windows.
You will need to install Python 3.9 and Node to run the web application. Then you will have to install the requirements. For more details, please read this guide: <https://github.com/FELT-Labs/federated-learning-token#quick-start>
