### ISSUE TITLE
AttributeError: 'Account' object has no attribute 'prvate_key'

### ISSUE THREAD

**Issue by baofu-han** [FELT-Labs/federated-learning-token#37]
<img width="907" alt="444CEEE7-AAAF-4F74-8D07-2D84C9CCAEB4" src="https://user-images.githubusercontent.com/44884594/194681559-c8380aa1-4434-4a1a-a64c-9d1886567665.png">
The  data type of owner obtained in this way is Account, but there is no private_key attribute in the Account. The private_key attribute exists only in the LocalAccount class.  How can I solve this problem?

**Comment by Breta01** [comment]
Hi, thank you for your interest in our project. I guess that you are using the `brownie test` command, which gives you this error? I updated the `requirements.txt`, please make sure you have the correct version of brownie installed (use `pip install -r rquirements.txt`). You also need to specify the `.env` file as described in `README.md` file
